In [1]:
#Create a numpy array
import numpy as np
arr = np.array([1,2,3,4,5])
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [2]:
# Creation of 0D array 

import numpy as np

arr = np.array(42)

print(arr)

42


In [3]:
#Creation of 1D array 

import numpy as np

arr = np.array([1,2,3,4,5])

print(arr)

[1 2 3 4 5]


In [5]:
#Creation of 2D array

import numpy as np

arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])

print(arr)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [6]:
# Creation of 3D array

import numpy as np

arr = np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])

print(arr)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


In [7]:
#Using ndimenssion to find dimenssion of array

import numpy as np

a = np.array(42)
b = np.array([1,2,3,4,5])
c = np.array([[1,2,3,4,5],[6,7,8,9,10]])
d = np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])
e = np.array([[[1,2,3],[4,5,6],[7,8,9]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)
print(e.ndim)

0
1
2
3
3


In [8]:
#Acess array elements

import numpy as np 

arr = np.array([1,2,3,4])

print(arr[1])

2


In [9]:
import numpy as np 

arr = np.array([1,2,3,4])

print(arr[0])

1


In [10]:
#Adding according to the index of array

import numpy as np 

arr = np.array([1,2,3,4])

print(arr[2] + arr[3])

7


In [11]:
#Acess 2D arrays

import numpy as np 

arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])

print('2nd element on the 1st row:',arr[0,1])

2nd element on the 1st row: 2


In [12]:
#Slicing index 

import numpy as np

arr = np.array([1,2,3,4,5])

print(arr[1:5])

[2 3 4 5]


In [13]:
#Slicing index 

import numpy as np

arr = np.array([1,2,3,4,5,6,7])

print(arr[:5])  #Here start of index is not given which is considered as 0 to 4 index

[1 2 3 4 5]


In [14]:
#Slicing index 

import numpy as np

arr = np.array([1,2,3,4,5,6,7])

print(arr[4:])  #Here end of index is not given which is considered as 4 to 6

[5 6 7]


In [15]:
#Slicing index 

import numpy as np

arr = np.array([1,2,3,4,5,6,7])

print(arr[:])  #Here start and end both of index is not given which is considered as 0 to 7 index

[1 2 3 4 5 6 7]


In [16]:
#Slicing index 

import numpy as np

arr = np.array([1,2,3,4,5,6,7])

print(arr[:4])  #Here start of index is not given which is considered as 0 to 3 index

[1 2 3 4]


In [17]:
# Negative Slicing index 

import numpy as np

arr = np.array([1,2,3,4,5,6,7])

print(arr[-3:-1])  #here -1 one element is not considered and also here index starts from behind and 0 index is not considered from right hand side 

[5 6]


In [18]:
#Slicing index 

import numpy as np

arr = np.array([1,2,3,4,5,6,7])

print(arr[1:5:2]) #here 2 means alternate slicing btw the start to end index means if i take it as 1:6:2 result would be 2,4,6

[2 4]


In [21]:
import numpy as np
arr =np.array([1,2,3,4,5,6,7])
print(arr[::2])

[1 3 5 7]
